# Generated by Django 4.1.5 on 2023-03-03 13:40

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commerical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ready_to_exchange', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('meter', models.IntegerField(blank=True, null=True)),
                ('year_of_construction', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_each_meter', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, choices=[('شخخصی', 'شخخصی'), ('املاک', 'املاک')], default='شخصی', max_length=200, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, max_length=450, null=True)),
                ('karkard_mashin', models.IntegerField(blank=True, null=True)),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_or_tip', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('گاز', 'گاز'), ('بنزین', 'بنزین'), ('گاز و بنزین', 'گاز و بنزین'), ('گازاایل', 'گازاایل')], max_length=100, null=True)),
                ('engin_type', models.CharField(blank=True, choices=[('سالم', 'سالم'), ('متوسط', 'متوسط')], max_length=100, null=True)),
                ('shasti_type', models.CharField(blank=True, choices=[('سالم', 'سالم'), ('متوسط', 'متوسط')], max_length=100, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('رنگ', 'رنگ'), ('بی رنگ', 'بی رنگ')], max_length=100, null=True)),
                ('insurance_time', models.IntegerField(blank=True, null=True)),
                ('girbox', models.CharField(blank=True, choices=[('دنده ای', 'دنده ای'), ('اتومات', 'اتومات')], max_length=100, null=True)),
                ('phone_status', models.CharField(blank=True, choices=[('دست دوم', 'دست دوم'), ('نو', 'نو')], max_length=100, null=True)),
                ('esalat', models.CharField(blank=True, choices=[('اصل', 'اصل'), ('تقلبی', 'تقلبی')], max_length=100, null=True)),
                ('sim_cart_number', models.IntegerField(blank=True, null=True)),
                ('memory_size', models.IntegerField(blank=True, null=True)),
                ('ram_size', models.IntegerField(blank=True, null=True)),
                ('window_size', models.CharField(blank=True, max_length=100, null=True)),
                ('os_typpe', models.CharField(blank=True, max_length=100, null=True)),
                ('game_pad_number', models.IntegerField(blank=True, null=True)),
                ('com_status', models.CharField(blank=True, choices=[('ویژه', 'ویژه'), ('ستاره دار', 'ستاره دار'), ('عادی', 'عادی')], max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commerical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commerical', to='core.commerical')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmallCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCommerical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('receiver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.thread')),
            ],
        ),
        migrations.CreateModel(
            name='CommericalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.comImagesPath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('commerical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commerical')),
            ],
        ),
        migrations.AddField(
            model_name='commerical',
            name='features',
            field=models.ManyToManyField(related_name='features', to='core.feature'),
        ),
        migrations.AddField(
            model_name='commerical',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.commerical'),
        ),
        migrations.AddField(
            model_name='commerical',
            name='saved',
            field=models.ManyToManyField(related_name='saved', to='core.savedcommerical'),
        ),
        migrations.AddField(
            model_name='commerical',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='core.tag'),
        ),
        migrations.AddField(
            model_name='commerical',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
