# Generated by Django 4.1.5 on 2023-03-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_commerical_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerical',
            name='day_rent_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
