# Generated by Django 4.1.5 on 2023-03-06 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_commerical_day_rent_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerical',
            name='com_status',
            field=models.CharField(blank=True, choices=[('ویژه', 'ویژه'), ('فوری', 'فوری'), ('ستاره دار', 'ستاره دار'), ('عادی', 'عادی')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commerical',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commerical',
            name='phone_status',
            field=models.CharField(blank=True, choices=[('نو', 'نو'), ('در حد نو', 'در حد نو'), ('کارکرده', 'کارکرده')], max_length=100, null=True),
        ),
    ]
