# Generated by Django 4.1.5 on 2023-03-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_location_location_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerical',
            name='smallCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.smallcity'),
        ),
    ]
