# Generated by Django 4.1.5 on 2023-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerical',
            name='com_status',
            field=models.CharField(blank=True, choices=[('ویژه', 'ویژه'), ('فوری', 'فوری'), ('ستاره دار', 'ستاره دار'), ('عادی', 'عادی')], default='عادی', max_length=200, null=True),
        ),
    ]
