# Generated by Django 4.1.5 on 2023-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_commerical_com_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerical',
            name='rent',
            field=models.CharField(blank=True, choices=[('کامل', 'کامل'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('7', '7')], max_length=100, null=True),
        ),
    ]
