# Generated by Django 4.1.5 on 2023-03-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_commerical_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerical',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
