# Generated by Django 4.1.5 on 2023-03-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_commerical_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerical',
            name='publisherForCar',
            field=models.CharField(blank=True, choices=[('همه', 'همه'), ('درخواست', 'درخواست'), ('فروشی', 'فروشی')], default='همه', max_length=200, null=True),
        ),
    ]
