# Generated by Django 4.1.5 on 2023-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_commerical_phone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerical',
            name='publisher',
            field=models.CharField(blank=True, choices=[('همه', 'همه'), ('شخصی', 'شخصی'), ('املاک', 'املاک')], default='شخصی', max_length=200, null=True),
        ),
    ]
