# Generated by Django 4.1.5 on 2023-03-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_commerical_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerical',
            name='farWork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commerical',
            name='max_price_for_work',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='commerical',
            name='min_price_for_work',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='commerical',
            name='soldier',
            field=models.BooleanField(default=False),
        ),
    ]
