# Generated by Django 4.1.5 on 2023-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_commerical_farwork_commerical_max_price_for_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commerical',
            name='max_price_for_work',
        ),
        migrations.RemoveField(
            model_name='commerical',
            name='min_price_for_work',
        ),
        migrations.AddField(
            model_name='commerical',
            name='price_for_work',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
