# Generated by Django 4.1.5 on 2023-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_commerical_max_price_for_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerical',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
    ]
