# Generated by Django 4.1.5 on 2023-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_commerical_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerical',
            name='anbari',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commerical',
            name='cloths_type',
            field=models.CharField(blank=True, choices=[('همه', 'همه'), ('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('بچگانه', 'بچگانه')], default='همه', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commerical',
            name='cover_simcart',
            field=models.CharField(blank=True, choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], default='ندارد', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commerical',
            name='internal_or_external',
            field=models.CharField(blank=True, choices=[('همه', 'همه'), ('داخلی', 'داخلی'), ('خارجی', 'خارجی')], default='همه', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commerical',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commerical',
            name='sanad_adari',
            field=models.CharField(blank=True, choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], default='ندارد', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commerical',
            name='simcartType',
            field=models.CharField(blank=True, choices=[('ایرانسل', 'ایرانسل'), ('همراه اول', 'همراه اول'), ('رایتل', 'رایتل')], default='ایرانسل', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commerical',
            name='color',
            field=models.CharField(blank=True, choices=[('همه', 'همه'), ('سفید', 'سفید'), ('مشکی', 'مشکی'), ('زرد', 'زرد'), ('آبی', 'آبی'), ('سبز', 'سبز'), ('قرمز', 'قرمز')], default='همه', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commerical',
            name='memory_size',
            field=models.IntegerField(blank=True, choices=[(4, 4), (8, 8), (16, 16), (32, 32), (64, 64), (128, 128), (256, 256)], default=4, null=True),
        ),
    ]
