# Generated by Django 4.1.5 on 2023-03-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_commerical_esalat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commerical',
            name='features',
        ),
        migrations.RemoveField(
            model_name='commerical',
            name='saved',
        ),
        migrations.AlterField(
            model_name='commerical',
            name='body_type',
            field=models.CharField(blank=True, choices=[('سالم و بی\u200cخط و خش', 'سالم و بی\u200cخط و خش'), ('رنگ', 'رنگ'), ('بی رنگ', 'بی رنگ'), ('خط و خش جزیی', 'خط و خش جزیی'), ('صافکاری بی\u200cرنگ', 'صافکاری بی\u200cرنگ'), ('رنگ\u200cشدگی', 'رنگ\u200cشدگی'), ('دوررنگ', 'دوررنگ'), ('تمام\u200cرنگ', 'تمام\u200cرنگ'), ('تصادفی', 'تصادفی'), ('اوراقی', 'اوراقی')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commerical',
            name='engin_type',
            field=models.CharField(blank=True, choices=[('سالم', 'سالم'), ('نیاز به تعمیر', 'نیاز به تعمیر'), ('تعویض شده', 'تعویض شده')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commerical',
            name='shasti_type',
            field=models.CharField(blank=True, choices=[('هر دو سالم و پلمپ', 'هر دو سالم و پلمپ'), ('عقب ضربه\u200cخورده', 'عقب ضربه\u200cخورده'), ('عقب رنگ\u200cشده', 'عقب رنگ\u200cشده'), ('جلو ضربه\u200cخورده', 'جلو ضربه\u200cخورده'), ('جلو رنگ\u200cشده', 'جلو رنگ\u200cشده'), ('عقب ضربه\u200cخورده، جلو رنگ\u200cشده', 'عقب ضربه\u200cخورده، جلو رنگ\u200cشده'), ('عقب رنگ\u200cشده، جلو ضربه\u200cخورده', 'عقب رنگ\u200cشده، جلو ضربه\u200cخورده'), ('هردو ضربه\u200cخورده', 'هردو ضربه\u200cخورده'), ('هردو رنگ\u200cشده', 'هردو رنگ\u200cشده')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commerical',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='core.tag'),
        ),
    ]
