# Generated by Django 4.1.5 on 2023-03-26 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_remove_commerical_features_remove_commerical_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerical',
            name='news',
            field=models.ManyToManyField(blank=True, null=True, related_name='news', to=settings.AUTH_USER_MODEL),
        ),
    ]
