# Generated by Django 4.1.5 on 2023-03-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_commerical_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerical',
            name='how_college_are',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commerical',
            name='how_we_pay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
