# Generated by Django 4.1.5 on 2023-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_commerical_how_college_are_commerical_how_we_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerical',
            name='sanad_adari',
            field=models.BooleanField(default=False),
        ),
    ]
