# Generated by Django 4.1.5 on 2023-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_commerical_sanad_adari'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerical',
            name='salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
