# Generated by Django 4.1.5 on 2023-03-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_commerical_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerical',
            name='floor',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='commerical',
            name='publisher',
            field=models.CharField(blank=True, choices=[('همه', 'همه'), ('شخخصی', 'شخخصی'), ('املاک', 'املاک')], default='همه', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commerical',
            name='rooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
