# Generated by Django 4.1.5 on 2023-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_commerical_floor_alter_commerical_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerical',
            name='sim_cart_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
